#CYCLE_TIME 10
#SEED 345
#ENDTIME 25000

#NEWPROCESS
#TYPE           NONINTERACTIVE
#NAME           COMPUTE
#SPAWNTIME      40
#WORKDURATION   5000
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_1
#SPAWNTIME      40
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_2
#SPAWNTIME      80
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_3
#SPAWNTIME      120
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_4
#SPAWNTIME      160
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_5
#SPAWNTIME      180
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_6
#SPAWNTIME      220
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_7
#SPAWNTIME      260
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_8
#SPAWNTIME      300
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_9
#SPAWNTIME      340
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_10
#SPAWNTIME      380
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_11
#SPAWNTIME      420
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_12
#SPAWNTIME      460
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_13
#SPAWNTIME      500
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_14
#SPAWNTIME      540
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_15
#SPAWNTIME      580
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_16
#SPAWNTIME      620
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_17
#SPAWNTIME      660
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_18
#SPAWNTIME      700
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_19
#SPAWNTIME      740
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_20
#SPAWNTIME      780
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_21
#SPAWNTIME      820
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_22
#SPAWNTIME      860
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_23
#SPAWNTIME      900
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_24
#SPAWNTIME      940
#ENDPROCESS

#NEWPROCESS
#TYPE           INTERACTIVE
#NAME           IO_25
#SPAWNTIME      980
#ENDPROCESS
