#CYCLE_TIME 10
#SEED 345
#ENDTIME 6000

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation
#SPAWNTIME	    40
#WORKDURATION	5000
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_ONE
#SPAWNTIME	    40
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWO
#SPAWNTIME	    80
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_THREE
#SPAWNTIME	    120
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FOUR
#SPAWNTIME	    160
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FIVE
#SPAWNTIME	    180
#ENDPROCESS
