#CYCLE_TIME	10
#SEED		43
#ENDTIME	1500

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation_One
#SPAWNTIME	    40
#WORKDURATION	200
#ENDPROCESS

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation_Two
#SPAWNTIME	    80
#WORKDURATION	200
#ENDPROCESS

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation_Three
#SPAWNTIME	    120
#WORKDURATION	200
#ENDPROCESS

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation_Four
#SPAWNTIME	    160
#WORKDURATION	200
#ENDPROCESS
