#CYCLE_TIME	10
#SEED		43
#ENDTIME	1000

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_ONE
#SPAWNTIME	    40
#KILLTIME	    900
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWO
#SPAWNTIME	    80
#KILLTIME	    900
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_THREE
#SPAWNTIME	    120
#KILLTIME	    900
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FOUR
#SPAWNTIME	    160
#KILLTIME	    900
#ENDPROCESS
