#CYCLE_TIME 10
#SEED 345
#ENDTIME 25000

#NEWPROCESS
#TYPE		    NONINTERACTIVE
#NAME		    Computation
#SPAWNTIME	    40
#WORKDURATION	5000
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_ONE
#SPAWNTIME	    40
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWO
#SPAWNTIME	    80
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_THREE
#SPAWNTIME	    120
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FOUR
#SPAWNTIME	    160
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FIVE
#SPAWNTIME	    180
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_SIX
#SPAWNTIME	    220
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_SEVEN
#SPAWNTIME	    260
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_EIGHT
#SPAWNTIME	    300
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_NINE
#SPAWNTIME	    340
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TEN
#SPAWNTIME	    380
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_ELEVEN
#SPAWNTIME	    420
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWELVE
#SPAWNTIME	    460
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_THIRTEEN
#SPAWNTIME	    500
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FOURTEEN
#SPAWNTIME	    540
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_FIFTEEN
#SPAWNTIME	    580
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_SIXTEEN
#SPAWNTIME	    620
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_SEVENTEEN
#SPAWNTIME	    660
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_EIGHTEEN
#SPAWNTIME	    700
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_NINETEEN
#SPAWNTIME	    740
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY
#SPAWNTIME	    780
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY_ONE
#SPAWNTIME	    820
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY_TWO
#SPAWNTIME	    860
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY_THREE
#SPAWNTIME	    900
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY_FOUR
#SPAWNTIME	    940
#ENDPROCESS

#NEWPROCESS
#TYPE		    INTERACTIVE
#NAME		    IO_TWENTY_FIVE
#SPAWNTIME	    980
#ENDPROCESS